### ISSUE TITLE
Fix bugs and dependency issues related to study_1

### ISSUE THREAD

**Issue by alperenyazmaci** [jsalzer312/SEArtifact-Group2#17]

**Comment by GoldenLin9** [comment]
Issue: Maven could not find these specific versions of the JAR files (appcore-1.1.jar and text-analyzer-1.2.jar) in the central Maven repository (https://repo.maven.apache.org/maven2).

Fix: I manually installed the missing JAR files into my local Maven repository using mvn install:[install-file] command. This command installs the JAR files directly into your local Maven repository (~/.m2/repository), allowing Maven to resolve the dependencies locally.

**Comment by GoldenLin9** [comment]
Issue: Missing commons-io dependency

- study_1/lucene/src/main/java/ComponentLocalization.java:[18,40] package org.apache.commons.io.comparator does not exist
- study_1/lucene/src/main/java/ComponentLocalization.java:[25,29] package org.apache.commons.io does not exist

Fix: add the following dependencies to study1/lucene/pom.xml

>  
       <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>2.11.0</version>
        </dependency>

**Comment by GoldenLin9** [comment]
Issue: Wrong path is mentioned in multiple places where it assumes there's a "real_data_construction" directory when it does not exist. Example: './study_1/real_data_construction/real_data/ob/obs.json' should be changed to 'study_1/dataset/real_data/ob/obs.json'

Fix: change the incorrect file path locations: study_1/sentence_bert/screen_and_component_localization.py, study_1/lucene/src/main/java/ScreenLocalization.java, study_1/lucene/src/main/java/ComponentLocalization.java, study_1/clip/screen_localization.py, study_1/clip/component_localization.py

**Comment by GoldenLin9** [comment]
Issue: NoClassDefFoundError: org/apache/commons/cli/ParseException

Fix: add the following dependencies to study1/lucene/pom.xml

> 
        <dependency>
            <groupId>commons-cli</groupId>
            <artifactId>commons-cli</artifactId>
            <version>1.4</version>
        </dependency>

**Comment by GoldenLin9** [comment]
Issue: NoClassDefFoundError: edu/stanford/nlp/pipeline/StanfordCoreNLP

Fix: add the following dependencies to study1/lucene/pom.xml

> 
        <dependency>
            <groupId>edu.stanford.nlp</groupId>
            <artifactId>stanford-corenlp</artifactId>
            <version>3.8.0</version>
        </dependency>
        <dependency>
            <groupId>edu.stanford.nlp</groupId>
            <artifactId>stanford-corenlp</artifactId>
            <version>3.8.0</version>
            <classifier>models</classifier>
        </dependency>

**Comment by GoldenLin9** [comment]
Issue: Missing dependency SLF4J
- SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
- SLF4J: Defaulting to no-operation (NOP) logger implementation
- SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.


Fix: add the following dependencies to study1/lucene/pom.xml

> 
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.7.32</version>
        </dependency>

**Comment by GoldenLin9** [comment]
Issue: The researchers assumed that people reproducing the research had 2 GPUs. This issue is seen with this line: `device = torch.device("cuda:1") if torch.cuda.is_available() else torch.device("cpu")`. cuda:1 is trying to index the second GPU since it is zero-based index.

Fix: Change cuda:1 to cuda:0 to use the first GPU. Affected file: study_1/clip/component_localization.py,
